server:
 port: 8092
spring:
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3306/user_db
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
 